include: all_lint_rules.yaml
linter:
  rules:
    always_put_control_body_on_new_line: false
    always_put_required_named_parameters_first: false
    always_specify_types: false
    always_use_package_imports: false
    avoid_annotating_with_dynamic: false
    avoid_catches_without_on_clauses: false
    avoid_classes_with_only_static_members: false
    avoid_final_parameters: false
    avoid_positional_boolean_parameters: false
    avoid_types_on_closure_parameters: false
    cascade_invocations: false
    close_sinks: false
    deprecated_member_use_from_same_package: false
    diagnostic_describe_all_properties: false
    do_not_use_environment: false
    flutter_style_todos: false
    lines_longer_than_80_chars: false
    matching_super_parameters: false
    omit_local_variable_types: false
    prefer_asserts_with_message: false
    prefer_constructors_over_static_methods: false
    prefer_double_quotes: false
    prefer_expression_function_bodies: false
    prefer_final_parameters: false
    prefer_int_literals: false
    public_member_api_docs: false
    require_trailing_commas: false
    sort_constructors_first: false
    unnecessary_final: false
    use_decorated_box: false
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test/.test_coverage.dart"
    - "bin/cache/**"
    - "lib/generated_plugin_registrant.dart"
  plugins:
    - "custom_lint"
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    included_file_warning: ignore
    missing_required_param: error
    missing_return: error
    record_literal_one_positional_no_trailing_comma: error
    collection_methods_unrelated_type: warning
    unrelated_type_equality_checks: warning
    deprecated_member_use_from_same_package: ignore
    parameter_assignments: warning
    todo: ignore
custom_lint:
  enable_all_lint_rules: true
