import 'package:flex_color_scheme/flex_color_scheme.dart';
import 'package:flutter/material.dart';

/// AppTheme class that provides the app theme data used by the app.
///
/// Theme config for FlexColorScheme version 7.3.x.
/// {@category Theme}
///
/// todo: update and modify as needed for the design

class AppTheme {
  static const CardTheme _cardTheme =
      CardTheme(margin: EdgeInsets.fromLTRB(18, 0, 18, 24));
  static final InputDecorationTheme _inputDecorationTheme =
      InputDecorationTheme(
    border: OutlineInputBorder(
      borderRadius: BorderRadius.circular(36),
    ),
  );

  static ThemeData toDark() => _toDark().copyWith(
        cardTheme: _cardTheme,
        inputDecorationTheme: _inputDecorationTheme,
      );
  static ThemeData toLight() => _toLight().copyWith(
        cardTheme: _cardTheme,
        inputDecorationTheme: _inputDecorationTheme,
      );

  static ThemeData _toDark() => FlexThemeData.dark(
        scheme: FlexScheme.gold,
        surfaceMode: FlexSurfaceMode.highBackgroundLowScaffold,
        blendLevel: 2,
        appBarStyle: FlexAppBarStyle.background,
        bottomAppBarElevation: 2.0,
        subThemesData: const FlexSubThemesData(
          blendOnLevel: 8,
          useTextTheme: true,
          useM2StyleDividerInM3: true,
          adaptiveElevationShadowsBack: FlexAdaptive.all(),
          adaptiveAppBarScrollUnderOff: FlexAdaptive.excludeWebAndroidFuchsia(),
          adaptiveRadius: FlexAdaptive.excludeWebAndroidFuchsia(),
          defaultRadiusAdaptive: 10.0,
          elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
          elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
          outlinedButtonOutlineSchemeColor: SchemeColor.primary,
          toggleButtonsBorderSchemeColor: SchemeColor.primary,
          segmentedButtonSchemeColor: SchemeColor.primary,
          segmentedButtonBorderSchemeColor: SchemeColor.primary,
          unselectedToggleIsColored: true,
          sliderValueTinted: true,
          inputDecoratorSchemeColor: SchemeColor.primary,
          inputDecoratorBackgroundAlpha: 22,
          inputDecoratorUnfocusedHasBorder: false,
          inputDecoratorFocusedBorderWidth: 1.0,
          inputDecoratorPrefixIconSchemeColor: SchemeColor.primary,
          fabUseShape: true,
          fabAlwaysCircular: true,
          fabSchemeColor: SchemeColor.tertiary,
          cardRadius: 14.0,
          popupMenuRadius: 6.0,
          popupMenuElevation: 3.0,
          alignedDropdown: true,
          dialogRadius: 18.0,
          useInputDecoratorThemeInDialogs: true,
          appBarScrolledUnderElevation: 3.0,
          drawerElevation: 1.0,
          drawerIndicatorSchemeColor: SchemeColor.primary,
          bottomSheetRadius: 18.0,
          bottomSheetElevation: 2.0,
          bottomSheetModalElevation: 4.0,
          bottomNavigationBarMutedUnselectedLabel: false,
          bottomNavigationBarMutedUnselectedIcon: false,
          menuRadius: 6.0,
          menuElevation: 3.0,
          menuBarRadius: 0.0,
          menuBarElevation: 1.0,
          menuBarShadowColor: Color(0x00000000),
          navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
          navigationBarMutedUnselectedLabel: false,
          navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
          navigationBarMutedUnselectedIcon: false,
          navigationBarIndicatorSchemeColor: SchemeColor.primary,
          navigationBarIndicatorOpacity: 1.00,
          navigationBarElevation: 1.0,
          navigationRailSelectedLabelSchemeColor: SchemeColor.primary,
          navigationRailMutedUnselectedLabel: false,
          navigationRailSelectedIconSchemeColor: SchemeColor.onPrimary,
          navigationRailMutedUnselectedIcon: false,
          navigationRailIndicatorSchemeColor: SchemeColor.primary,
          navigationRailIndicatorOpacity: 1.00,
          navigationRailBackgroundSchemeColor: SchemeColor.surface,
        ),
        visualDensity: FlexColorScheme.comfortablePlatformDensity,
        useMaterial3: true,
      );
  static ThemeData _toLight() => FlexThemeData.light(
        scheme: FlexScheme.gold,
        surfaceMode: FlexSurfaceMode.highBackgroundLowScaffold,
        blendLevel: 1,
        appBarStyle: FlexAppBarStyle.background,
        bottomAppBarElevation: 2.0,
        subThemesData: const FlexSubThemesData(
          blendOnLevel: 6,
          blendOnColors: false,
          useTextTheme: true,
          useM2StyleDividerInM3: true,
          adaptiveRemoveElevationTint: FlexAdaptive.excludeWebAndroidFuchsia(),
          adaptiveElevationShadowsBack: FlexAdaptive.excludeWebAndroidFuchsia(),
          adaptiveAppBarScrollUnderOff: FlexAdaptive.excludeWebAndroidFuchsia(),
          adaptiveRadius: FlexAdaptive.excludeWebAndroidFuchsia(),
          defaultRadiusAdaptive: 10.0,
          elevatedButtonSchemeColor: SchemeColor.onPrimaryContainer,
          elevatedButtonSecondarySchemeColor: SchemeColor.primaryContainer,
          outlinedButtonOutlineSchemeColor: SchemeColor.primary,
          toggleButtonsBorderSchemeColor: SchemeColor.primary,
          segmentedButtonSchemeColor: SchemeColor.primary,
          segmentedButtonBorderSchemeColor: SchemeColor.primary,
          unselectedToggleIsColored: true,
          sliderValueTinted: true,
          inputDecoratorSchemeColor: SchemeColor.primary,
          inputDecoratorBackgroundAlpha: 19,
          inputDecoratorUnfocusedHasBorder: false,
          inputDecoratorFocusedBorderWidth: 1.0,
          inputDecoratorPrefixIconSchemeColor: SchemeColor.primary,
          fabUseShape: true,
          fabAlwaysCircular: true,
          fabSchemeColor: SchemeColor.tertiary,
          cardRadius: 14.0,
          popupMenuRadius: 6.0,
          popupMenuElevation: 3.0,
          alignedDropdown: true,
          dialogRadius: 18.0,
          useInputDecoratorThemeInDialogs: true,
          appBarScrolledUnderElevation: 1.0,
          drawerElevation: 1.0,
          drawerIndicatorSchemeColor: SchemeColor.primary,
          bottomSheetRadius: 18.0,
          bottomSheetElevation: 2.0,
          bottomSheetModalElevation: 4.0,
          bottomNavigationBarMutedUnselectedLabel: false,
          bottomNavigationBarMutedUnselectedIcon: false,
          menuRadius: 6.0,
          menuElevation: 3.0,
          menuBarRadius: 0.0,
          menuBarElevation: 1.0,
          menuBarShadowColor: Color(0x00000000),
          navigationBarSelectedLabelSchemeColor: SchemeColor.primary,
          navigationBarMutedUnselectedLabel: false,
          navigationBarSelectedIconSchemeColor: SchemeColor.onPrimary,
          navigationBarMutedUnselectedIcon: false,
          navigationBarIndicatorSchemeColor: SchemeColor.primary,
          navigationBarIndicatorOpacity: 1.00,
          navigationBarElevation: 1.0,
          navigationRailSelectedLabelSchemeColor: SchemeColor.primary,
          navigationRailMutedUnselectedLabel: false,
          navigationRailSelectedIconSchemeColor: SchemeColor.onPrimary,
          navigationRailMutedUnselectedIcon: false,
          navigationRailIndicatorSchemeColor: SchemeColor.primary,
          navigationRailIndicatorOpacity: 1.00,
          navigationRailBackgroundSchemeColor: SchemeColor.surface,
        ),
        visualDensity: FlexColorScheme.comfortablePlatformDensity,
        useMaterial3: true,
        // To use the Playground font, add GoogleFonts package and uncomment
        // fontFamily: GoogleFonts.notoSans().fontFamily,
      );
}
