name: "Macos Build"
description: "Builds an Zip for Macos using Flutter."
inputs:
  token:
    description: "GitHub Token"
    required: true
  ref-name:
    description: "GitHub Ref Name"
    required: true
runs:
  using: "composite"
  steps:
    - name: Enable macOS build
      shell: bash
      run: flutter config --enable-macos-desktop

    - name: Build artifacts
      shell: bash
      run: flutter build macos --release
    
    - name: Build dmg
      shell: bash
      run: appdmg installers/dmg_creator/config.json installers/dmg_creator/dohc_bible_ppt.dmg

    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: dohc_bible_ppt_macos.dmg.zip
        directory: installers/dmg_creator
          
    - name: macOS Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      env:
          GITHUB_TOKEN: ${{ inputs.token }}
      with:
        files: installers/dmg_creator/dohc_bible_ppt.dmg.zip