name: Flutter Analyze and Test
on:
  push:
    branches:
      - main
      - release/*
  pull_request:
  workflow_dispatch:
jobs:
  Flutter-Analyze-And-Test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Triggered by ${{ github.actor }} on a ${{ github.event_name }} event."
          echo "And is running on a ${{ runner.os }} agent."

      - name: Runner Software Versions
        run: |
          git --version
          jq --version

      - name: Check out ${{ github.repository }} - ${{ github.ref }}
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: ./.github/actions/install-and-configure-flutter
          
      - name: Flutter Get, Gen, Analzye, and Test
        uses: ./.github/actions/flutter-get-gen-analzye-test
      
      - run: echo "${{ github.job }} status ${{ job.status }}."
