name: Macos Build Release 🚀

on:
  workflow_dispatch:
  push:
    branches:
      - feature/cicd

jobs:
  Macos-Build-Release:
    defaults:
      run:
        shell: bash
    runs-on: macos-latest

    steps:
      - run: |
          echo "Triggered by ${{ github.actor }} on a ${{ github.event_name }} event."
          echo "And is running on a ${{ runner.os }} agent."

      - name: Runner Software Versions
        run: |
          git --version
          jq --version

      - name: Check out ${{ github.repository }} - ${{ github.ref }}
        uses: actions/checkout@v4

      - name: Get App Name and Version
        id: get-app
        uses: ./.github/actions/get-app-name-and-version

      - name: Install Flutter
        uses: ./.github/actions/install-and-configure-flutter

      - name: Flutter Get, Gen, Analzye, and Test
        uses: ./.github/actions/flutter-get-gen-analzye-test
      
      - name: Macos Build
        uses: ./.github/actions/macos-build
        with:
          token: ${{ secrets.TOKEN }}
          ref-name: ${{ github.ref_name }}
      